### ISSUE TITLE
Posición del arduino mega en la tarjeta modulo_arduino.

### ISSUE THREAD

**Issue by rvega** [miguelitoVargas/seqExplora#11]
El borde izquierdo del PCB del Arudino Mega debe estar al ras con el borde izquierdo del PCB modulo_arduino. La razón es: El arduino vá a quedar en sanduche entre el panel de control (lámina metalica) y el modulo_arduino, entonces necesitamos que los conectores USB y Power del arduino queden visibles (saliendo).

**Comment by miguelitoVargas** [comment]
ya quedo, revisalo para ver si se mueve mas
