### ISSUE TITLE
Error en Kicad al abrir modulo_arduino

### ISSUE THREAD

**Issue by rvega** [miguelitoVargas/seqExplora#12]
Sale este mensaje de error:

``` 
The following libraries were not found:
/home/tc/ides_frameworks/kicad/footprints/arduino-kicad-library/arduino 
```
El esquemático y el PCB parecen estar completos y bien. Hay alguna opción en Kicad de "guardar con todas las dependencias" o algo asi?

**Comment by miguelitoVargas** [comment]
es esta libreria para arduino
https://github.com/Alarm-Siren/arduino-kicad-library
estan todas o casi las pcbs de arduino, hacer un submodulo o que instales la libreria en el tuyo

**Comment by rvega** [comment]
Arreglado. Hacé pull.
