### ISSUE TITLE
Layout.

### ISSUE THREAD

**Issue by rvega** [miguelitoVargas/seqExplora#5]
Vamos a tener un montón de cables ribbon llegando a los headers de esta tarjeta. Por esto, mejor tener mas espacio entre un header y otro. Tanto vertical como horizontalmente. Me gusta la disposición en filas y columnas que tenés pero mientras menos apeñuscado, mejor.

**Comment by miguelitoVargas** [comment]
quedaron mas separados, revisa, yo creo que asi esta bien pero creo que se pueden separar mas

**Comment by rvega** [comment]
#8
