### ISSUE TITLE
Espacio de "protoboard"

### ISSUE THREAD

**Issue by rvega** [miguelitoVargas/seqExplora#7]
Acordate de poner un espacio con una cuadricula de pads para poder poner algunos componentes adicionales en la PCB, por si las moscas.

**Comment by rvega** [comment]
El espacio entre pads debe ser el mismo que en un header, creo que es 2.54mm pero no tengo como verificar en este momento.

**Comment by rvega** [comment]
Si, es 2.54mm.

https://en.wikipedia.org/wiki/Pin_header

**Comment by miguelitoVargas** [comment]
hay de varios pero si standard es 2.54mm

**Comment by rvega** [comment]
Veo que ya lo pusiste en los 2 PCBs, cerrando.
