### ISSUE TITLE
Espacio entre headers de leds en tarjeta modulo_botones.

### ISSUE THREAD

**Issue by rvega** [miguelitoVargas/seqExplora#8]
Los headers de 5x1 donde se conectan los leds pueden estar mas separadosen la dirección Y.  Porfa separarlos lo mas que se pueda para que al conectar los ribbons sea mas sencillo.

**Comment by rvega** [comment]
Lo mismo los headers de 3x1 que se usan para los pots, un poco mas de espacio.

**Comment by miguelitoVargas** [comment]
creo que ya no se podrian separar mas, revisa y comenta
